name = "ACS"
uuid = "7c442146-1877-4809-8980-097e62f18350"
authors = ["Saer Samanipour, PhD", "Env Modeling & Computational Mass Spec Lab (EMCMS)"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
